services:
  - type: web
    name: portfolio-backend
    env: node
    buildCommand: |
      echo "Current directory: $(pwd)"
      echo "Directory contents: $(ls -la)"
      echo "Checking for server directory..."
      if [ -d "server" ]; then
        echo "Server directory found"
        cd server && npm install
      else
        echo "Server directory not found!"
        echo "Available directories: $(find . -type d -maxdepth 1)"
        exit 1
      fi
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production 