services:
  - type: web
    name: portfolio-fullstack
    env: node
    buildCommand: |
      echo "Installing server dependencies..."
      npm install
      echo "Installing client dependencies..."
      cd client
      npm install
      echo "Cleaning previous build..."
      npm run clean
      echo "Building client..."
      npm run build
      echo "Verifying build..."
      ls -la dist
      echo "Checking index.html..."
      if [ -f dist/index.html ]; then
        echo "index.html found"
      else
        echo "index.html not found!"
        exit 1
      fi
      echo "Moving back to root directory..."
      cd ..
      echo "Verifying client build location..."
      if [ -d "client/dist" ]; then
        echo "Client build found in correct location"
        ls -la client/dist
      else
        echo "Client build not found in expected location!"
        exit 1
      fi
      echo "Build completed successfully!"
    startCommand: NODE_ENV=production node server/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: ADMIN_USERNAME
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: CLIENT_URL
        value: https://briewubet.onrender.com
      - key: PORT
        value: 10000 