services:
  - type: web
    name: portfolio-fullstack
    env: node
    buildCommand: |
      npm install
      cd client && npm install && npm run build:prod
      cd ..
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: ADMIN_USERNAME
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: CLIENT_URL
        value: https://portfolio-fullstack.onrender.com 